development:
  adapter: postgresql
  encoding: unicode
  database: fotografias_dev
  pool: 5
  username: fotos
  password: fotos

test:
  adapter: postgresql
  encoding: unicode
  database: fotografias_test
  pool: 5
  username: fotos
  password: fotos